-- Wafier KB seed (18 chunks)
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('SDAIA', 'نظام حماية البيانات الشخصية (PDPL)', 'ينظم معالجة البيانات الشخصية بما فيها بيانات الاستهلاك المنزلي المرتبطة بفرد محدد.', 'https://sdaia.gov.sa/ar/SDAIA/about/Pages/AboutPDPL.aspx') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('SDAIA', 'PDPL — تحديد الغرض', 'يجب جمع البيانات لأغراض محددة وصريحة؛ الاستخدام الثانوي (مثل الإعلانات) يتطلب أساساً قانونياً منفصلاً وموافقة.', 'https://sdaia.gov.sa/ar/SDAIA/about/Pages/AboutPDPL.aspx') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('SDAIA', 'PDPL — إخفاء الهوية للتحليل', 'قبل تصدير بيانات الأسرة لمسار ML يجب إزالة المعرفات أو استخدام معرفات مجهولة.', 'https://sdaia.gov.sa/ar/SDAIA/about/Pages/AboutPDPL.aspx') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('SDAIA', 'PDPL — منع إعلانات من بيانات الاستهلاك', 'استخدام أنماط استهلاك الكهرباء للإعلانات المستهدفة دون موافقة منفصلة يتجاوز غرض إدارة الميزانية.', 'https://sdaia.gov.sa/ar/SDAIA/about/Pages/AboutPDPL.aspx') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('SDAIA', 'مبادئ أخلاقيات الذكاء الاصطناعي الوطنية', 'يجب أن تكون مخرجات الذكاء الاصطناعي شفافة وقابلة للتفسير؛ التوقعات تقديرية وليست ضماناً مالياً.', 'https://sdaia.gov.sa/') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('SDAIA', 'SDAIA — الإشراف البشري', 'يحق للمستخدم التحكم في التنبيهات الآلية؛ Wafier يوفّر إيقاف التنبيهات مؤقتاً (HITL).', 'https://sdaia.gov.sa/') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('SAMA', 'إطار الخدمات المصرفية المفتوحة', 'ينظم مشاركة البيانات المالية بموافقة المستهلك؛ حدود Wafier: بيانات العداد ليست مصرفية إلا عند ربط حساب بنكي مستقبلاً.', 'https://openbanking.sama.gov.sa/index-en.html') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('SAMA', 'حماية المستهلك — SAMA', 'يجب الإفصاح الواضح للمستهلك؛ يُطبّق مبدأ الإفصاح على تنبيهات التوقع في Wafier.', 'https://www.sama.gov.sa/en-US/RulesInstructions/Pages/ConsumerProtection.aspx') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('SAMA', 'إطار الأمن السيبراني — SAMA', 'مرجع لأمن البيانات عند تكامل Wafier مع خدمات مالية مستقبلية.', 'https://www.sama.gov.sa/en-US/RulesInstructions/CyberSecurity/Cyber%20Security%20Framework/Pages/default.aspx') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('CMA', 'مختبر التقنية المالية — CMA', 'بيئة تنظيمية تجريبية لمنتجات FinTech مبتكرة في أسواق المال.', 'https://fintech.cma.org.sa/') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('KAUST / SEC', 'KAUST وSEC — تعلم آلي لخسائر الشبكة', 'يُشجّع استخدام ML في قطاع الكهرباء السعودي؛ سياق شرعي لتوقعات الاستهلاك.', 'https://www.kaust.edu.sa/news/kaust-helps-slash-sec-profit-losses-using-ml') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('SEC', 'الشركة السعودية للكهرباء', 'مزوّد الكهرباء الوطني؛ سياق التعرفة السكنية وخدمات العداد.', 'https://www.se.com.sa/') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('SEC / KAUST context', 'تعرفة الكهرباء السكنية (تنفيذ Wafier)', 'الشريحة الأولى حتى 6000 ك.و.س/شهر بـ 0.18 ر.س/ك.و.س؛ التالية 0.30 ر.س/ك.و.س؛ ضريبة 15%.', 'https://www.kaust.edu.sa/news/kaust-helps-slash-sec-profit-losses-using-ml') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('KAPSARC', 'KAPSARC — كفاءة الطاقة والذكاء الاصطناعي', 'سياق كفاءة الطاقة وتطبيقات الذكاء الاصطناعي في قطاع الطاقة.', 'https://www.kapsarc.org/media/ip0dt4i1/dp00503-v1.pdf') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('KAPSARC', 'KBEAT — تحليل كفاءة المباني', 'نصائح توفير الطاقة في المنازل السعودية: 24-26°C للمكيف، عزل حراري، LED.', 'https://apps.kapsarc.org/appboard/kbeat/en') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('MDPI Energies', 'ML for energy consumption forecasting in KSA', 'مرجع أكاديمي لتوقعات استهلاك الطاقة في السعودية.', 'https://www.mdpi.com/1996-1073/16/4/2035') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('Google DeepMind', 'DeepMind — تبريد مراكز البيانات', 'مثال على تحسين التبريف بالذكاء الاصطناعي؛ سردي لموجات الحر.', 'https://deepmind.google/discover/blog/deepmind-ai-reduces-google-data-centre-cooling-energy-by-40/') ON CONFLICT DO NOTHING;
INSERT INTO regulation_chunks (source, title, content, url) VALUES ('ITU-T', 'ITU-T Y.3172', 'إطار خط أنابيب ML: SRC, Collector, PP, Model/MLFO, Sandbox, Policy, Distributor, SINK.', 'https://www.itu.int/rec/T-REC-Y.3172-201906-I') ON CONFLICT DO NOTHING;
